### PR TITLE
Force Picasso not to store images in its cache

### PR DESCRIPTION
**Pull request by jayzes**
Some combination of the picker showing and the image resizing is causing memory pressure, which would result in a trim event being fired and the page being reloaded in the middle of the upload process.

This does a few things to address that:

- Update Crosswalk to the latest stable (22.52.561.4)
- Set the `android:largeheap` setting in the manifest
- Use the `RGB_565` setting for image reprocessing in Picasso
- Prevent `trimMemory` events from triggering a reload while picking images

It does now seem that the Crosswalk picker does not return the image capture intent back properly in a way that the image gets processed, which appears to be unrelated but could also cause memory pressure.

### CODE REVIEW

**Comment by jayzes** [comment]
@steam updated this PR with the scorched-earth approach, if you want to take another look. Seems to have fixed the issue in a few tests with @Justin-Holmes though it'll take more real-world testing to see if it fixes the issue more broadly.

**Comment by Justin-Holmes** [comment]
🔥 🌎 :metal:

**Comment by mkitt** [comment]
💣 💥

**Comment by jayzes** [comment]
Closing since this is no longer relevant.

**Pull request closed without merging**
